-- Oracle 11g (XE). IDENTITY no existe en esta versión.
-- Si la tabla se creó con IDENTITY, elimínala antes:
-- DROP TRIGGER USERS_BI;
-- DROP TABLE USERS;
-- DROP SEQUENCE USERS_SEQ;

CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE USERS (
    ID NUMBER(19) PRIMARY KEY,
    FIRST_NAME VARCHAR2(100) NOT NULL,
    LAST_NAME VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(30),
    EMAIL VARCHAR2(255) NOT NULL,
    PASSWORD_HASHED VARCHAR2(255) NOT NULL,
    ROL VARCHAR2(50) NOT NULL,
    CONSTRAINT UK_USERS_EMAIL UNIQUE (EMAIL)
);

CREATE OR REPLACE TRIGGER USERS_BI
BEFORE INSERT ON USERS
FOR EACH ROW
WHEN (NEW.ID IS NULL)
BEGIN
    SELECT USERS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
